### ISSUE TITLE
msgbox creator code umlauts issue

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#100]
1) when using umlauts in Title / Message, the inserted code is incorrect
[![quirk6.png](https://s11.postimg.org/srprgwtwj/quirk6.png)](https://postimg.org/image/e8imfi0rj/)
2) this may be related to [issue 97](https://github.com/maestrith/AHK-Studio/issues/97)
3) Suggestion: for consistency reasons, in msgbox creator "Message" shold read "Text" (like in the actual MsgBox Command) or maybe Message Text (as a ref to the msgbox command) ?

**Comment by maestrith** [comment]
I updated the plugin to fix the issue.  Alt+M Download Plugins and check MsgBox Creator to get the update (it "should" already be checked)

**Comment by megabugman** [comment]
plugin updated, now Msgbox Creator Test fails!

to repro, use "русскиеÖÖÖä" as Title and Message
[![quirk6.gif](https://s13.postimg.org/6ql0tzdwn/quirk6.gif)](https://postimg.org/image/3whvgjbqb/)

**Comment by maestrith** [comment]
well that's odd... I'll see what I can do.

**Comment by maestrith** [comment]
Should be fixed.  Update the plugin again and it should work.  I may end up adding this to the main script.  Also if it is fixed please close this thread :)

**Comment by megabugman** [comment]
> Also if it is fixed please close this thread :)
this time, Timeout is broken.
[![quirk7.gif](https://s12.postimg.org/vorg1gp7x/quirk7.gif)](https://postimg.org/image/i7uhilew9/)

**Comment by maestrith** [comment]
oops, fixed

**Comment by megabugman** [comment]
you're fast :) 
confirmed, seems fixed.
