### ISSUE TITLE
1 Omni Search issue and 3 suggestions

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#101]
1) running Omni Search from itself closes the window
to repro, press ^!o, type omni, double click "Omni Search" to close it.
2) Suggestion 1: make  Omni Search moveable
eg. via LMouse Btn pressed then allow drag
3. Suggestion 2: the window starts with vert/horz scroll-bars visible & window size and position is not saved.
Save & Restore the position.
4. Suggestion 3: add "Message" fuzzy search string in Omni Search in order to find the MsgBox Creator by "Message"

**Comment by maestrith** [comment]
1. Removed it from the list.  I honestly forgot to do that and all it does it try to run itself so it was pointless.
2. I will try.
3. I will look into that.
4. I'll have to think about what to have in the Edit field.

**Comment by megabugman** [comment]
confirmed, issue # 1 is fixed.

**Comment by megabugman** [comment]
closed due to inactivity

**Comment by maestrith** [comment]
Issue #3
-I have not had the issue of it not saving its position. Please let me know how to re-produce this issue.
![capture](https://cloud.githubusercontent.com/assets/2114637/26665595/d6128720-4668-11e7-85d2-9dd3942fad5e.gif)
