### ISSUE TITLE
Add a menu here issue

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#102]
select some text, move mouse, right mouse click
loop, 7
 {
   move mouse
   right mouse click
 }
[![quirk11.gif](https://s7.postimg.org/tbf5pyzmj/quirk11.gif)](https://postimg.org/image/mxq2mpuqf/)

**Comment by maestrith** [comment]
I "think" I fixed this.

**Comment by megabugman** [comment]
fixed
