### ISSUE TITLE
unusable context menu commands should be grayed out

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#104]
select some text, cut it, move the cursor, press RMB, 
-> the context menu commands Cut, Copy & Delete should be greyed out (like in Notepad)
[![notgreyedout.png](https://s21.postimg.org/i7gzas8p3/notgreyedout.png)](https://postimg.org/image/wdwq60jk3/)

**Comment by maestrith** [comment]
Should be addressed in the latest 1.003.13

**Comment by megabugman** [comment]
not fixed in 1.003.13
[![quicks19.gif](https://s21.postimg.org/pa9oyvfon/quicks19.gif)](https://postimg.org/image/ldwd2vuoz/)

**Comment by maestrith** [comment]
did you try to check for update? I did fix it but I didn't advance the version number

**Comment by megabugman** [comment]
ups. got it now.
fixed.

**Comment by maestrith** [comment]
:) let me know if you want to chat.  I have Google Hangouts or Skype.
