### ISSUE TITLE
cursor position not saved / restored correctly when (un)commenting

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#105]
set cursor somewhere between a word then press shift F1
the cursor position is lost, cursor moves to first char in row.

select as shown to even teleport the cursor to the script beginning by a sole +F1
[![quicks17.gif](https://s7.postimg.org/vbb27awdn/quicks17.gif)](https://postimg.org/image/tji3ced0n/)

**Comment by maestrith** [comment]
yea, that causes a lot more issues than just that.  The way I designed it is so that you put your cursor on line 10, in your example, then press Shift+F1, but I can see that being a problem.  I will see if I can fix it.

**Comment by megabugman** [comment]
fixed
