### ISSUE TITLE
code folding incorrect mouse cursor

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#106]
when hovering the mouse over the code folding +/- the mouse cursors changes to an I-beam pointer, which is generally used to enter text.
[![quicks18.gif](https://s32.postimg.org/rwnui1739/quicks18.gif)](https://postimg.org/image/4ifv63p5t/)

**Comment by maestrith** [comment]
This is going to be a multi-hour thing to figure out...I am working on a lot at the moment but I will get to it.

**Comment by megabugman** [comment]
[notepad2mod ](https://xhmikosr.github.io/notepad2-mod/) is Scintilla based and supports code folding, here's the [source ](Code folding). Is that of any help?

**Comment by maestrith** [comment]
The way that I have to wrestle with the cursor I am not too sure.  It took about 6 months to get the main GUI to function the way that it does (poorly I know) but AHK is just not that friendly with the mouse cursor.

**Comment by maestrith** [comment]
wait a sec...

**Comment by maestrith** [comment]
![capture](https://cloud.githubusercontent.com/assets/2114637/23388115/5713a838-fd2e-11e6-8dd0-7f4dbbc70fe6.gif)
It doesn't seem to be doing it to me...

**Comment by megabugman** [comment]
wow, it works now!
i don't understand how you did that. I launched an old version and it works. 
is studio updating in the background?

**Comment by maestrith** [comment]
it shouldn't be.  you should have to Check For Updates for it to even look to see if there is an update.  Then click the button to update on the dialog that opens.

**Comment by megabugman** [comment]
fixed
