### ISSUE TITLE
inconsistent dirty flag

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#107]
create new project, press enter, dirty flag set in projects window & Title.
hit !r -> notice inconsistency
[![quicks20.gif](https://s1.postimg.org/6xuug6g67/quicks20.gif)](https://postimg.org/image/68c23tfmj/)

maybe related to issue [#77](https://github.com/maestrith/AHK-Studio/issues/77) ?

**Comment by maestrith** [comment]
I will get to this, but it is going to be a lot of coding to get the * to react properly

**Comment by megabugman** [comment]
don't waste too much time on this one, it's not a big deal (for me).

**Comment by maestrith** [comment]
to be honest, it'll be a long while before I get to this one...

**Comment by megabugman** [comment]
maybe there is a simple solution. assuming the file status in the title is always correct, why not simply clone the flag from there?

**Comment by megabugman** [comment]
closed due to inactivity
