### ISSUE TITLE
incorrect numbering alingment in Notes

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#108]
ctrl+MouseWheel to zoom in, numbering unreadable and cannot be accessed by horizontal scrollbars
[![numbering.png](https://s17.postimg.org/7chpk44gf/numbering.png)](https://postimg.org/image/s9dxos2h7/)

**Comment by maestrith** [comment]
Should be fixed

**Comment by megabugman** [comment]
fixed
