### ISSUE TITLE
Online Help  Formatting Corrupted

### ISSUE THREAD

**Issue by kwoodhouse** [maestrith/AHK-Studio#116]
The online help content has been corrupted.  There is no separation between topics:

![image](https://cloud.githubusercontent.com/assets/6086755/24403494/2a805bc2-138b-11e7-9426-b3575cd0d19a.png)

**Comment by maestrith** [comment]
oh wow...wonder what I did there.

**Comment by kwoodhouse** [comment]
Thanks.
