### ISSUE TITLE
Gui error

### ISSUE THREAD

**Issue by magicstep** [maestrith/AHK-Studio#117]
The following line (1255) caused an error:
`Gui,%dg%:Default`

I "fixed" it like this
`Gui,new:Default`

I'm a noob and I don't know if that affected some functionality, but it works.
AHK-Studio Version: 1.003.1
AHK Version v1.1.22.09

**Comment by maestrith** [comment]
I notice that you are on version 1.003.1 and I am at version 1.003.21.  I think I might have addressed the issue you are referring to.  Press Alt+M and type CFU {enter} (Check For Update) and update the script.  If the error persists please let me know, but if not go ahead and close this issue.

**Comment by magicstep** [comment]
I updated both AHK-Studio and AHK.
All works fine.

**Comment by maestrith** [comment]
Glad to hear it :)
