### ISSUE TITLE
UI messed up

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#121]
i somehow managed to mess up the UI. after max. the window, some elements "float" around. maybe you know the reason and how to fix it.
![messedup](https://user-images.githubusercontent.com/17204819/28185533-01f98bec-6818-11e7-9423-260abfd94742.PNG)

**Comment by maestrith** [comment]
How to fix it:
1. Close Studio
2. Delete lib\Gui.xml
3. Re-Open Studio
Reason:
Not 100% sure sadly.  I haven't had it happen in a very long time and I can not get it to re-create so that I can fix it.

**Comment by megabugman** [comment]
this is how it looks "restored".
![restored](https://user-images.githubusercontent.com/17204819/28185786-f338de18-6818-11e7-9d1e-c2d94539f159.PNG)
the session is running, are you interested in a memory dump?

**Comment by maestrith** [comment]
Not necessary, I'm always trying to figure out what can cause it but so far I am coming up with nothing.
