### ISSUE TITLE
Wrong syntax detection in raw text

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#124]
As the picture shows, syntax detection and highlighting for raw text is wrong and it can even mess up the program's syntax in lines after the text.
![image](https://user-images.githubusercontent.com/6554605/29240260-8f1b8244-7f76-11e7-86f0-8c7034c47367.png)

**Comment by maestrith** [comment]
oh boy... this'll take some time to fix....

**Comment by maestrith** [comment]
Hopefully it is fixed. Go ahead and Alt+M CFU {enter}

**Comment by ali80** [comment]
yeah, beautiful, works like a charm, Great job by the way. Now it becomes my main editor again :)
I'm that much in love with this that I wish it supported other languages and extensions as well. I'm much happier in your editor than in notepad++ or sublime, though not as feature rich as others, the features that are implemented do work better.
