### ISSUE TITLE
encoding?

### ISSUE THREAD

**Issue by clu--** [maestrith/AHK-Studio#125]
Hi and thank you for your nice work,
  I just saw your AHK Studio via the videos in YT. So I thought i'd give it a try
  and ran it presto... to discover that when opening my files i see a lot of gibbrish
  where i used to see commonly accentuated characters or drawn lines : my encoding is
  basically UTF8 and i couldn't find an option to switch encodings.
  The truth is that i come from notepad2-mod which allows me to select the current
  encoding or even to convert/export between "compatible" encodings without loss (based
  on same scintilla lib i believe.
  Any advice? an option to be found somewhere, a file to tweak, a future version to
  come? hope?
  I appreciate your kind attention

JClu--

sample (to be pasted into AHK studio to realize the  problem): 
```
┌────────┐
│ voilà  │
└────────┘
```

**Comment by maestrith** [comment]
Yea, I have tried like crazy to get it to figure out encoding.  If you create a file in Notepad (original) and save it as UTF-8 encoding it works properly.

I am going to try to figure out a way to make all files be read as UTF-8

**Comment by clu--** [comment]
Wow, this is too fast, beyond any axpectation...
  thank you for your prompt reply.
  actually my files are already in UTF8 but don't render correctly in AS.
  It's probably normal since only the files in UTF8 with the so called BOM are supposed to be recognized 
    whereas the no BOM ones are seen as mere ansi. but in np2 i can swith it encoding (well actually nowadays
    i do it all in utf8 so no bother).
   i'm no core dev (just the few script in AHK to aliviate my days automating some repetitive tasks but, maybe, you could
   see what they did with np2 (they even brought up a new np3 i'm not using... don't feel) :
     https://github.com/XhmikosR/notepad2-mod
     https://github.com/rizonesoft/Notepad3

   thank you in advance.
clu
2017081520219

Hmmmm : may i ask if there is a place to ask some requests :-) just to see some things in there, if possible. merci.




----- Chad Wilson <notifications@github.com> a écrit :

**Comment by maestrith** [comment]
1.003.24
Added: Reported by clu-- (and I'm sure many others) #125
-Options/Force UTF-8: This will force Studio to open and write all files to UTF-8

Let me know if this helps.

**Comment by clu--** [comment]
well, it somehow, somewhere displays somethings OK...
but makes a mess of everything else. Probably to much of a trouble to handle.
It's just that ANSI is just good for english, i'm luso-french and play with asian languages on occasion....
I'll see how i'll handle it my side.
I play with html files for the mixed languages but if you wanna see how things break, you can also have one of my .ahk (if you promise not to laugh at it poor coding see the attached file) : 
AS has trouble displaying all correctly (compare with another plain text editor) and does not process the whole file till the end. So, for the moment i'll sadly avoid it (already regretting its powerful features).
Back later when this (harmful to my files) aspect is overcome.
However I'm very glad to see the good work being done that easy competes with the huge marted toys out there. Thank you for sharing it and even dedicate some time to my difficulties.
encore merci!

clu
2017081520757

PS : at the end of the .ahk, some (commented) piece of one of the (<pre> formatted) htm files so you can have a taste of both worlds in one place... tested before sending in np2 and AS to confirm a very ast time.
[w0.zip](https://github.com/maestrith/AHK-Studio/files/1224281/w0.zip)

**Comment by clu--** [comment]
ooooops : did close, not intended, my bad.

clu
2017081520814

**Comment by maestrith** [comment]
Thank you for the example :) I have not sadly figured out how to read the text of an Ansi encoded file with UTF characters yet.  For the moment open the file in Notepad and Save As and choose UTF-8 for encoding and it "should" open properly in Studio.

**Comment by maestrith** [comment]
Wow, I think I might have it fixed.  Make sure you have Options/Force UTF-8 enabled, and it "should" work...

**Comment by clu--** [comment]
OK :  Options/Force UTF-8 enabled before loading anything into last master.zipped AS....
well, not there yet : 
1. still breaks files before EOF
2. probs dealing with line drawing and co.
sorry.
clu
2017081630307

**Comment by maestrith** [comment]
Can you please provide me with some examples? I have tried it with your w0.ahk file and it seems to work.  I would be interested to see what I am doing wrong.

**Comment by clu--** [comment]
Strange : using same ol'w0.ahk i made the attached screenshot with it opened in  np2 & AS side by side.
And i definitely get the prior probs visible :
  1. AS still breaks files before EOF (see : line 197 (AS) vs. 209 (NP))
  2. probs dealing with line drawing and co (as seen with the last boxes)
UTF8 is set and works with the accents though not the lines... "bizarre".
Ow, and another problem : with all files closed, the option needs to be checked twice before sticking.
However, next restart of AS and gone it is.
![2017081632346-npvsas](https://user-images.githubusercontent.com/10607342/29387259-7be582b2-82df-11e7-8bc6-95dc49fb1fc4.png)

**Comment by clu--** [comment]
Just realized you had commited a new fix. Tested... sorry this time it even broke @ line 192.
another thing i did not notice with the previous SS : when the about dialog open, it changes the title of the main window to "AHK Studio - \" causing even another confusion... <<what was the file i was editing again?>>
Now I start feeling bad for bringing those (weird and somehow unimportant) things up while i'm enthusiastic with all the uncomparably  cool features AS you'd put together in it.
than you for givin me some attention,
clu
201708174 -- 0102

**Comment by clu--** [comment]
Hmmm, now, reading this msg via my email makes me realize my replies on the forum cannot be satisfactory. And for a *good* -sic- rizon:
  they just want to get it done to see the nice fireworks at the end and ignore what lies in every case of "why can't i see it".
  In fact, as it occurs often with experts (and i'm the same in my work) they seem not to hve any trouble with the tools they master.
  well, that's cause they master it so well that they don't even realize they keep compensating for the deficiencies of the tool itself.
  And what i call tool covers a wide range of *things* :
   1- computer apps like the one we're dealing here
   2- any material machine we use in our daily lives
   3- but also any intellectual tool :
     a- languages (like the spoken/written/sign/braille/or any other mean of exchanging information=)
     b- concepts/representations/models/beliefs used to ground our decisions/actions
     c- institutions/group structures/teams we erly on to accomplish whatever
     d- goals/projects/hopes (yeah, could be included in b... with an humph) that keep us moving

  Now, what happens is that the new comer, not endowed with that mastery, unable to filter our the existing asperities of the tools,
  will, unavoidably and eventually, bump into them, face them as the actual raoadblocks they are. She's being th fresh eye the optimist
  master seeks in the naive, innocent new follower or the dumb, stupid, imbecile, good for nothing and somewhat arrogant apprentice the
  negative master can never accept/understand : come on! how difficult can it be to do things right!
  
  My opinion on the matter : life/histoy always gets to have the last word (or is it death, i always mix it). All i can is observe and
  chose the strategy i wanna adopt in such a situation be it as a master or as new comer. So what follows is an *incomplete* of the many
  different choices one has :
    A- for the master :
      1. get rid of the new comer and maybe even reject any new ones
      2. suck it up, do like nothing happens, live with it, even progress he's own way while bearing it in the darkest places of his tortured mind
      3. face it and work on a solution to the iferences between him and her :
          a- teach her, share the mastery with, make a master out of the rough clay she is to him...
              when other new comers are bound to come... well at least now they'll be two facing the problem (like a horde of zombies in recent movies)
          b- address the problem at the tool level, and make it *smarter* ( like the phone ever kid in town -and in the country- have in hand these days)
              thus the problem disappears and, actually, even He shall enjoy the mindless/effortless use of the features the tool provides 
                  like when He's tired, sick... or just distracted, cause He'sstill human after all :-)
        ...
    A- for the new comer :
      1. keep it all for herself, and either seek another master, become one or just give it all up
      2. do like nothing actually bothers her, ligtens her heart with some other stuff, wait and see what things come around
      3. gets it bad, shoot at everything and everyone around (including the Master, how dareful fool)
      4. faces it, points the finger at it, calls a poo a poo, and :
          a- mentions it to the Master and see what comes out
          b- leads a new revolutionnary mouvement that will rock the senile order
        ...      
   These are not the only ways to deal with *situations*, just trying to cover most cses History provides us with... far from done.
   Yet, i'd prefer choice 3b for the Master and 4a for the apprentice... but that's not taking into account the actual circumstances they might be facing
   so it cannot be a serve it all way of doing.

My cheap piece of philo in this story to, say, practice my poor english into treading unfamiliar grounds.

Now, where are we? Ow, yes, UTF8 and AHK Studio (AS)...
In order to reproduce my problem here more details on my story : iwas born in... what? no relevant? really? OK!

conf : 
  OS : win7 (pro, french) 
  data : the w0.ahk already provided
  AS : latest at time of this post : 1.003.24 returned by help>about
  AHK : 1.1.26.01
scenario :
  . got pristine AS freshly downloaded, decompressed into its own forlder and no changes made to any of the files.
  . start the AHK-Studio.ahk file
  . "option>Force UTF-8" (twice as it only remains active after that)
  . drag-and-drop w0.ahk to the opened AS window : file opens
  . go to the end of file and there i see :
      . non ansi characters are not rendered correctly (but work fine in np2 or open in a browser with encoding set to UTF-8)
      . the file is not displaid in its entirety : all the lines are dropped past a certain line
  . also noticed : 
    . close AS,
    . reopen AS :
       the "option>Force UTF-8" is not active anymore.
      
that's all i can think of to report... hmm maybe this :
  i manage files with a commander like file manager (more precisely : double commander) and thus the drag-and-drop was made
    from that file manager (and not windows explorer) to AS : dunno if this matter but thought i should say it all.
  anything missing to complete the equation?
  just ask, this long prose should tell you i care for your work and expect much out of it (no pressure intended, wel..;not much :-)

clu
201708174 -- 0526  

----- Chad Wilson <notifications@github.com> a écrit :

**Comment by maestrith** [comment]
I'm not too sure why, but sometimes it will report Force UTF-8 being set when the option isn't set.  Try this for me.
1. Close AHK Studio
2. Open lib\Settings.xml and look for
  	<options Manual_Continuation_Line="1" Full_Auto_Indentation="1" Focus_Studio_On_Debug_Breakpoint="1" Word_Wrap_Indicators="1" Context_Sensitive_Help="1" Auto_Complete="1" Auto_Complete_In_Quotes="1" Auto_Complete_While_Tips_Are_Visible="1" Force_UTF-8="1"></options>
  Yours will look different but make sure that Force_UTF-8="1" and not "0"
3. Save and then re-open AHK-Studio
4. Re-open the file.

**Comment by clu--** [comment]
YEESSSH!
  it worked! 
   (i mean complete file display, drawing lines and all. Even with the following restarts.)
  hmmmmm.... wait there.... does it mean i'll have to do this kind of stuff every now and then?
  guess not, mostly because :
    + why wouldn't the master i get already fiddled that way if this was THE key?
            (and thus displaying the "option>force..." as active at first)
    + and what about the way the option is/isn't visualy shown cheched upon selected?
      I tried the following once *U=1* in settings.xml and all works :
        1. open AS with w0.ahk : all is well as said above
        2. in menus : uncheck (once) force-UTF8 : a. appears unchecked in menu, b. nothing changed in the way w0.ahk is shown (good... which is not coherent).
        3. restart AS : a. w0.ahk goes back to be shown broken and b. the option still appears unchecked in menu
        4. in menus : 
        case a.
          a.1. check (once) force-UTF8 : a. appears unchecked in menu(!!), b. nothing changed in the way w0.ahk is shown (broken... coherent with menu display but not my checking it).
          a.2. restart AS : a. w0.ahk is shown correctly and now b. the option appears checked in menu (opposite of what was shown after single check and before restart!!!)
        case b.
          b.1. check (twice) force-UTF8 : a. appears checked in menu(!!), b. nothing changed in the way w0.ahk is shown (broken... *NOT* coherent with menu display).
          b.2. restart AS : a. w0.ahk is still shown broken and b. the option appears unchecked again in menu  (opposite of what was shown after single check and before restart!!!)
       ... these scenari should, hopefully, point to where the problem raises from.

bonne chance!
clu
201708174 -- 1623

----- Chad Wilson <notifications@github.com> a écrit :

**Comment by maestrith** [comment]
As long as the XML file has U=1 then it should be fine.  What it does when you Force UTF-8 is that it'll treat all files as having UTF-8 encoding and will save it accordingly.  So when you unchecked UTF-8 and re-opened it, it has already been formatted correctly when it saved so Studio knows that it is a UTF-8 file and can open it properly.  AutoHotkey has issues with files that do not have the proper formatting (I "think" without the BOM but I can not be sure) but when it re-writes it with the right formatting, it knows what to do with it.

**Comment by clu--** [comment]
i see it as a given that non-BOM signed UTF8 content cannot be identified as so for the very reason it doen't bear any id of it. This is part of the reason i asked for a user selection rather than an automagic one.
In fact i even referred to np2's way of doing (and most web browsers too) : you get a default encoding in the app settings and user can change the default on a "per file/url" basis (or could we do per some spec basis, or keeping track/history per file, sorry, got carried away :-).
What could also be done is export/import to/from a distinct encoding, again à la np2...
why not even embed np2 (as it is gpl'd)... i think too far again.

thanks anyway since with this manual trick i see it keeping the settings steadily, so... i'll give it a longer trial.
good work Chad,

clu
201708174 -- 2158

**Comment by clu--** [comment]
No reaction? 
So probably this issue is considered covered.... though i'd like more on the encoding side.
OK then, let opt for a fixed encoding for the moment.
Thank you for adding that featue.

cli
201708207 -- 0833
