### ISSUE TITLE
Toggle Comment line uncomments the comments!

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#128]
When comments that start with ";" are mixed with code, executing the toggle comment line command comments the code but uncomments the comments.
I get the problem,maybe make your comments unique so that this command doesn't effect user comments, or use two different keys one for commenting and the other for uncommenting(maybe ^+j), I like the latter more since your comments would be the same as user comments and also the new command can also uncomment user comments.

**Comment by maestrith** [comment]
There is a setting called Build Comment Alt+M Build {Enter} that was made for this exactly.

**Comment by ali80** [comment]
oh, I didn't notice that, there are so many features :), thanks

**Comment by maestrith** [comment]
No problem :) I know there is a ton of features to Studio and it is not possible to know all of them.  I even forget about half of them.

**Comment by ali80** [comment]
So maybe if possible make another video or even explain the features and workflow that you use most.
The video that you made with Joe though great and although it was long didn't cover much.

**Comment by maestrith** [comment]
LOL! yea, I'm eventually going to make a series of videos but when I look at the amount of them I would have to make I just get overwhelmed and just watch YouTube videos...

**Comment by ali80** [comment]
hehe, it seems everyone have the same problem, they say the key is to break the job down to smaller pieces, though that didn't work for me either :D
