### ISSUE TITLE
Variables starting with numbers get completely highlighted as a number

### ISSUE THREAD

**Issue by Run1e** [maestrith/AHK-Studio#130]
https://i.imgur.com/uhJGnGL.png

**Comment by maestrith** [comment]
Let me know if you are still getting this issue, if not go ahead and close this thread :) Thanks for the heads up!

**Comment by Run1e** [comment]
I'm not sure if this is what you intended, numbers is variable names are still highlighted if it's first in the var name: https://i.imgur.com/Eb6xkhr.png

If this is what you wanted then I'll close the issue.

**Comment by maestrith** [comment]
Maybe delete SciLexer.dll and rerun Studio. I "think" I fixed it and it just isn't updating the SciLexer file.

**Comment by Run1e** [comment]
Had it redownload SciLexer.dll -> https://i.imgur.com/mfZT8yZ.png

**Comment by maestrith** [comment]
Right, what are you expecting? For it to just be all the same color as the text?
