### ISSUE TITLE
ctrl-shift-esc wont work when ahk-studio is active

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#135]
the shortcut key to open task manager doesn't work when ahk-studio is active

**Comment by maestrith** [comment]
I believe I have that set as a hotkey for something.  Let me check

**Comment by maestrith** [comment]
Yes, it is the hotkey for Insert_Code_Vault_Text.  Alt+M EH{enter} and type in Insert Code Vault Text into the search bar at the top of that window and change the hotkey

**Comment by ali80** [comment]
well this is a very useful shortcut and I've never seen any program override it, I suggest not to invade window's commonly used shortcuts :)

**Comment by maestrith** [comment]
to be fair, I had no idea it was a windows shortcut until long after I set it up.  I removed it.
