### ISSUE TITLE
ahk-studio saves changes before exit without asking

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#137]
if you have unsaved changes in your document, ahk-studio automatically saves them on the original files before closing which is not what you want.
there are two options here,
1.ask before saving and closing
2.have a sandbox like notepad++ or sublime which stores the unsaved changes there before closing and restore that on the next run. this is only when you close the program , if you want to close an unsaved tab they both always ask before closing which makes sense.

**Comment by derz00** [comment]
Studio is set to automatically save all files when closing. This can maybe changed in the settings or code. :)

**Comment by FearlessPotatoKing** [comment]
Where can i find the setting to disable this? 

I tried enabling "Disable Autosave" but that wasn't it, and none of the other options within the "Settings" screen hinted at disabling this feature.
