### ISSUE TITLE
Inconsistency between same file opened from different locations of sidebar!

### ISSUE THREAD

**Issue by ali80** [maestrith/AHK-Studio#139]
This bug in conjunction with issue #137 could be quite dangerous.
All of the files included in ahk studio are shown in a tree view under the main file (call it main.ahk) which included them. so that's one way of opening the included files, also if you open the included file (call it function.ahk) with ahk studio it will appear outside of the main file tree, so there are two ways to open the function.ahk file but oddly it seems that there are two instances of the same file in ahk studio which changing one wont result in changing the other.

**Comment by maestrith** [comment]
So if you try open Function.ahk and it is a part of an open Project already then maybe not allow it to open?
