### ISSUE TITLE
Saving file

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#142]
When you start a new file in Studio, it imports the default template. Hitting Ctrl + S does not bring up the Save File dialogue, until you make a change to the code...

**Comment by maestrith** [comment]
Correct, there isn't much need to save an item if it is an Untitled.ahk file that hasn't been changed.

**Comment by derz00** [comment]
:) I see your point, but if I am starting a new project, I sometimes want to get this part over with right away: find a place to put it and save it there; even before I start typing anything... It's normal behaviour in programs like MS Office, etc, which is why I mentioned it. I don't miss it that much, now that I think of it. 🤦‍♂️  👋

**Comment by maestrith** [comment]
There is an option I believe it is called new file dialog or something similar to that I am not at my computer so I cannot recall but it will ask you for the new file name to save before it even shows the new file

**Comment by derz00** [comment]
Great, it's an option you can enable a dialog when creating a new file. Just right, thanks!

**Comment by maestrith** [comment]
Yep, it is called "New File Dialog" let me know if that works.

**Comment by derz00** [comment]
It does, thanks a lot
