### ISSUE TITLE
Saving file with extension other than .ahk

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#144]
In the Save File dialog, you can select `All Files (*.*)` but if you enter an extension other than .ahk, it adds .ahk onto the end.

**Comment by maestrith** [comment]
Yea, I don't know how to detect when the user selects *.* but I will think of something.  I will make this a part of the newest update, but the way to fix this for now is to add the extension to Alt+M MFT {Enter} (Manage File Types) and add the extension that you want to use.  It "should" make it so that extension will not add the extra .ahk afterward.

**Comment by maestrith** [comment]
I now have a way to detect this.  It will be a part of the next major update.  Thank you for this bug report :) I learned something.

**Comment by maestrith** [comment]
You can try this out in the Beta branch. https://raw.githubusercontent.com/maestrith/AHK-Studio/Beta/AHK-Studio.ahk

**Comment by derz00** [comment]
It seems something was reverted in between version 1.005.00 and 1.005.09? 

It works to save with other extensions with x.09 with "All Files" selected, but the file types options are different. Was that intentional?

**Comment by maestrith** [comment]
I tested and I think it is working as intended.
Save As with AutoHotkey filter selected and saving Testing.ahk.ext will save the file as Testing.ahk.ext.ahk
Saving file with All Files Testing.ahk.ext would be Testing.ahk.ext
The only time that an extension can be anything other than the filter is on All Files (*.*)

**Comment by derz00** [comment]
OK, yes it works. Something was different for version 1.005.00, because the AHK filter was called "Personal File types" or something, and had all the custom file types included. But it seems the custom extensions still work, they just don't show on the GUI. No big deal. 
And I think there was a separate filter for *.txt files, but that isn't necessary.
Keep up the good work. ;)

**Comment by maestrith** [comment]
Thanks :) I will keep trying.
