### ISSUE TITLE
Omni-Search window does not closes after selecting "Save As"

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#146]
**Test Plan:**

1. Press Alt + M
2. Type `sa` then Enter
3. Press Cancel (or go ahead and Save something As 👍 )
4. Mission completed, you're back at Studio, with the Omni-Search window still there.

**Version:**
* 1.005.00

**Comment by derz00** [comment]
Updated to the latest beta, 1.005.09, and the same thing happens.

**Comment by maestrith** [comment]
Will be fixed in the next Beta release

**Comment by maestrith** [comment]
Should be fixed in the Beta
