### ISSUE TITLE
Highlighting issue Beta: 1.005.09

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#147]
![image](https://user-images.githubusercontent.com/30033758/32739341-885e450a-c86d-11e7-94b0-11c084d9c6a0.png)
`:=` immediately after variable makes highlighter think it is a label

**Comment by maestrith** [comment]
You can change the color of the Labels and Variables in Theme
![image](https://user-images.githubusercontent.com/2114637/32834326-3c8762e2-c9d0-11e7-90fc-75841f1c3abb.png)

**Comment by derz00** [comment]
I knew that, but I thought something wasn't working right, because when there is a space like `Variable :=`, the variable is white.

**Comment by maestrith** [comment]
nope, the Scintilla control is a bit odd when you start adding spaces for too many things.

**Comment by derz00** [comment]
I see sorry

**Comment by maestrith** [comment]
no need to be sorry :) I just don't want to bog it down too much.

**Comment by derz00** [comment]
Just to tease you, did you ever consider making it *pure* AHK? 😛 [RichCode.ahk by G33kDude](https://github.com/G33kDude/RichCode.ahk) I'm sure he'd support that. 😆 But there's no doubt a lot of work involved to get the same features as Scintilla. Probably there'd be even more bugs

**Comment by maestrith** [comment]
it would run like trash.  I have tried and I didn't have half of what I have in Studio now and it was taking forever to do anything.  AHK isn't fast enough.
