### ISSUE TITLE
Indents after commands

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#148]
AHK Studio Beta automatically indents the next line after entering a command, etc (after which you wouldn't normally indent) when the file extension is different than `.ahk` (But it is in my personal extensions list)

**Comment by maestrith** [comment]
What sort of file, and what command?

**Comment by maestrith** [comment]
Also if you could include the file that would be great.

**Comment by derz00** [comment]
I have been using `.ahk2` to allow for running both versions of AutoHotkey. Attached is a test file.
[test.txt](https://github.com/maestrith/AHK-Studio/files/1493302/test.txt)

You're evidently *on*line 👍

**Comment by maestrith** [comment]
And you didn't create a ahk2.xml file? Just so we are on the same page

**Comment by derz00** [comment]
No, wouldn't be that smart :)

**Comment by maestrith** [comment]
aww, don't say that.  I'll make a bit of a tutorial on how to make one....eventually.

Anyway, I'll look into it.

**Comment by maestrith** [comment]
oh wow...yea, that's not good.  I will see what I can do.

**Comment by derz00** [comment]
Thank you.
Do I open a Github issue for every problem like this I have with Studio? Or where can I ask you simple questions?

**Comment by maestrith** [comment]
I put in a quick fix. Force an update if it doesn't say there is one....which it probably won't.  I'll push an official update when I get a few more things fixed up.

**Comment by derz00** [comment]
Uh, yes, there was an update, but it didn't change the version number (1.005.00). There wasn't an update there when I told it to check a couple days ago. And, yes, now the indent seems to work (doing further testing)

**Comment by derz00** [comment]
No, it doesn't quite work. It doesn't indent at all now, for example after `if` `loop` etc
.ahk files still work

**Comment by maestrith** [comment]
I don't always change the version numbers.  If it does not show "No new updates" (or whatever I put in there I honestly can't remember) then the code has been updated.

**Comment by maestrith** [comment]
Right, if there isn't a control file for the file type, like .txt or .ahk2, it will not know that anything needs indented.  I am changing Studio to work with multiple languages.  Do you call the files .ahk2 ?

**Comment by derz00** [comment]
Would the last line be more like this, with ahk2? (to clarify what you say) Sorry, but I feel insecure with this yet, and didn't want to get confused. `<FileTypes lexer="ahk" language="ahk" name="AutoHotkey2">ahk2 txt whatever</FileTypes>`

**Comment by derz00** [comment]
I think I will make a `ahk2.xml` to tweak syntax, etc

**Comment by maestrith** [comment]
`<FileTypes lexer="ahk" language="ahk" name="AutoHotkey2">ahk2 txt</FileTypes>`
That should work if you want .txt to work.  I think that is a great idea :)

**Comment by derz00** [comment]
Did you make `ahk.xml` all by hand or could you automate it with data from the documentation?

**Comment by maestrith** [comment]
a little bit of both to be honest.  I had to write something to build the syntax and the <Context> area was something I had to write completely by hand.  <Code> was also something I have been working on for a few years to get "right"

**Comment by derz00** [comment]
I am having problems with editing the theme. Does it work for you in beta? Changes are inneffective...

**Comment by maestrith** [comment]
which things in theme are you trying to change?

**Comment by derz00** [comment]
matching braces, and variables colour. I click on it, change it, but the examples in the theme do not change, and clicking them again, the settings are back to the original.

**Comment by maestrith** [comment]
is this for .ahk files or .ahk2?

**Comment by derz00** [comment]
I didn't know there is a difference? It behaves the same when either of the two is the selected script

**Comment by derz00** [comment]
Where's the next best place to talk to you besides Discord or opening GitHub issues? ;)

**Comment by maestrith** [comment]
Up to you, I'm on Discord right now but you let me know where would be the best place to chat about this.

**Comment by derz00** [comment]
#ahk irc is easiest for me to grab right now. Otherwise forum PM (not instant though
