### ISSUE TITLE
Toggle Comment Line (debug leftovers?)

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#150]
Hello, I had AHK Studio Beta Release, and there was an update for it today, and now it says 1.003.31 in the title of the Check for Update window. The current changelog says the latest is 1.005.09. Is the number in the title wrong or do I not have the beta anymore?

Anyway, whatever version I have, when I use the Toggle Comment Line feature, a msgBox asks "here?" and after pressing OK, it toggles the comment, and ends with a tooltip (That doesn't go away) that has this:
```;
40
40
something else I can't remember
```

👍 Just to let ya know

**Comment by maestrith** [comment]
that was a test message I forgot to remove.  I will update that soon.
