### ISSUE TITLE
Auto-indent command?

### ISSUE THREAD

**Issue by GollyJer** [maestrith/AHK-Studio#165]
Hi. I'm new to AHK Studio. 
Is there a command that auto-indents the open file?  Or is auto-indent only applied as you type?

Thanks!

**Comment by maestrith** [comment]
Alt+M Fix Indent{Enter}

**Comment by GollyJer** [comment]
Thanks!  Not sure why I haven't tried AHK-Studio before.  This is awesome!

Building a theme right now.  Not totally intuitive but starting to look good.
Is there a way to format the gutter background?
![image](https://user-images.githubusercontent.com/689204/36620644-00c1bc4e-18c2-11e8-8d9f-cea65dff1ebb.png)

**Comment by maestrith** [comment]
Hold Alt and Left Click the Line Numbers. I'd be happy to do a voice chat with you on Discord, Skype or Hangouts if you are interested.

**Comment by GollyJer** [comment]
Thanks again @maestrith. I was able to get a skin I'm happy with.

Closing this issue.
