### ISSUE TITLE
Themes crashing Studio

### ISSUE THREAD

**Issue by Graushwein** [maestrith/AHK-Studio#167]
At first, I patched to latest and it wouldn't allow me to use the old theme, incompatible. 
[NuclearDragon.zip](https://github.com/maestrith/AHK-Studio/files/1832087/NuclearDragon.zip)

Also the caret line background isn't working for me. But I can live without that.

**Comment by maestrith** [comment]
[NuclearDragon.zip](https://github.com/maestrith/AHK-Studio/files/1835550/NuclearDragon.zip)
That "should" work.

**Comment by maestrith** [comment]
What about the caret line isn't working? Did you enable it with Alt+M Show Caret Line{Enter} ?

**Comment by Graushwein** [comment]
The caret line just doesn't highlight. I did it in options and nothing happened. But that just made it work. Thanks! And the file worked too!
