### ISSUE TITLE
problem with include

### ISSUE THREAD

**Issue by derz00** [maestrith/AHK-Studio#168]
Here's the 2 include lines in my script.

![image](https://user-images.githubusercontent.com/30033758/38034127-9a53f2c0-326f-11e8-88c2-27900127a2a8.png)

And here's the files of the two functions, which are in the main script's directory.

[functions.zip](https://github.com/maestrith/AHK-Studio/files/1856293/functions.zip)

When I run the main script from AHK Studio, I get a AHK error--"#Include file ... cannot be opened". When I run the script from the folder, it works fine. Any ideas what's wrong? I had thought it might be a difference between 32 and 64 bit, because Studio runs itself with 32 bit, but my custom Run plugin uses the default (64).

**Comment by maestrith** [comment]
Try to use Alt+M Refresh Current Project and see if that helps.

**Comment by derz00** [comment]
This is getting scary. I guess it's not a problem with Studio. But something does not seem right. The only place anymore that I can run this script, with the function files in the directory as described, is by running it from Windows Explorer. And a script I have that starts my AHK scripts also gets it going. But copying those lines from the start up script and running them does not work. Any other way does not work, as far as I can tell. I'm almost doubting my own brain. Sorry for bothering you.

**Comment by maestrith** [comment]
Zip up the entire script and send it to me.  I'll see if it works the same on my system.

**Comment by derz00** [comment]
Ain't gonna bother at the moment :) It isn't the best designed project just now. Sometime I'll try to improve it and then see what happens.
