### ISSUE TITLE
AHK-Studio will not open anymore

### ISSUE THREAD

**Issue by SkiperTheBoss** [maestrith/AHK-Studio#173]
Hi,
my AHK-Studio got randomly closed/crashed, i was writing on my script and pressed the Hotkey to run the script but the Studio got frozen and will not start again.

Here is there Error: [https://i.imgur.com/BpC5lgf.jpg](https://i.imgur.com/BpC5lgf.jpg) 

So what could i do to help and fix it?

**Comment by maestrith** [comment]
Delete the file in Studio Dir\Lib called Gui.xml, or you can try to figure out in that file what the width value "should" be but that is often times a headache.  Just know if you delete the Gui.xml file it will revert to the default view.

**Comment by maestrith** [comment]
In a folder <Your Studio Folder>\Lib\XML Backup\Gui there will be 5 XML files.  Choose the most recent one of those and copy that to the <Your Studio Folder>\Lib folder changing the name to Gui.xml and overwriting the one that is there.

**Comment by SkiperTheBoss** [comment]
Alright, that works,

Thanks

**Comment by maestrith** [comment]
No problem :)

**Comment by maestrith** [comment]
s
