### ISSUE TITLE
issue saving

### ISSUE THREAD

**Issue by sl5net** [maestrith/AHK-Studio#183]
i cot this error today sometimes. if i save it by using fils>save as and confirm yes to overwrite i able to do it.

BTW is there a way to open the file without starting debugger or run the file?

---------------------------
AHK Studio
---------------------------
There was an issue saving ...\global-IntelliSense-everywhere-Nightly-Build\ActionLists\MozillaWindowClass\Mozilla_Firefox.ahk
Please close any error messages and try again

**Comment by sl5net** [comment]
1) if i save by using the menu. it works.
2) if i save using shortcut i got sometimes the message above.
probably interaction with other scripts (thanks and sorry).

BTW i think 1) works becouse then activeWindow (is a menu) is something else.

**Comment by maestrith** [comment]
What sort of shortcut are you using?  That error should only happen if there is an issue backing up the current file.  I'd be happy to use some sort of Voice/Screen share like TeamViewer to debug the issue on your system.
