### ISSUE TITLE
Disable Keyboard Steal Focus while within AHKStudio

### ISSUE THREAD

**Issue by FearlessPotatoKing** [maestrith/AHK-Studio#184]
I've been trying to search through settings to see if I can find a toggle to disable the default state of stealing keyboard focus and using it only for AHKStudio. 

Example: I have my f3 key mapped to launch Search Everything. But it does not function while i'm within AHKStudio. 

I also have other ahk scripts like RadialMenu or ClipJump that will not function while I have AHKStudio activated. 

Is there any way to disable this feature? It really interrupts my workflow and navigation habits.

**Comment by maestrith** [comment]
I have not heard of Studio doing that to anyone.  I'd be happy to have a chat on Discord, Skype, Hangouts, Team Viewer, or whatever screen sharing/voice chat software you like just let me know.  Alt+M EH {Enter} for Edit Hotkeys which I am sure you already found and disabling any associated hotkeys should free them up away from AHK Studio.  Alt+M DH {Enter} (Display Hotkeys) will show you what keys Studio has reserved.

**Comment by FearlessPotatoKing** [comment]
That fixed my issue for me. 
I removed the hotkeys that weren't working for me and that fixed my issue. 

And then for RadialMenu (also written in AutoHotKey) it turned out that it wasn't displaying because it was checking to see if "ahk_class AutoHotkeyGUI" existed already, and if it did, not display the menu. 

Since both programs are written in AutoHotKey they both share the same ahk_class.  Your software is working perfectly and it was user error all the way. 

Thanks for your help.
