### ISSUE TITLE
"code explorer" unvisible

### ISSUE THREAD

**Issue by sl5net** [maestrith/AHK-Studio#188]
i there a possibility to visible "code explorer" again?
i could not find it.

i searching something like code explorer (like https://cdn2.techworld.com/cmsdata/downloads/33099/img3File_thumb800.png?version=9%2E9 )

i saw that at the beginning. now its hidden. may i moved a border to the edge. may a possibility to set back to default sizes?

![2018-10-12 02_41_54-global-intellisense-everywhere-nightly-build e__fre_private_htmldevelop_autohot](https://user-images.githubusercontent.com/5634759/46841470-72eba800-cdc8-11e8-97be-bc67074190f7.png)

**Comment by maestrith** [comment]
Right Click the main area, Split Control/Right/Code Explorer

**Comment by sl5net** [comment]
thanks. that halps me so much ! :)
