### ISSUE TITLE
Add setting: clear debugwindow on start

### ISSUE THREAD

**Issue by dmtr99** [maestrith/AHK-Studio#206]
It would be helpfull to add a option to clear the debugwindow when running a script.
Currently, in every script I write I add a line to clear the debugwindow.
DebugWindow("",Clear:=1)

I would also update the function debugwindow to only work if AHK Studio is running.
This way you do not need to remove the lines when distributing the script to other people.
Something like:
```
DebugWindow(Text,Clear:=0,LineBreak:=0,Sleep:=0,AutoHide:=0,MsgBox:=0){
	if WinExist("AHK Studio - ")
		x:=ComObjActive("{DBD5A90A-A85C-11E4-B0C7-43449580656B}"),x.DebugWindow(Text,Clear,LineBreak,Sleep,AutoHide,MsgBox)
}
```

**Comment by dmtr99** [comment]
I found the option "CLEAR DEBUN ON RUN", this is what I was looking for.

**Comment by maestrith** [comment]
Sorry I missed this question.  I have been working on developing for Android and kind of got lost.
