### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by pmcmillan99** [maestrith/AHK-Studio#214]
Not sure what I hit but my font is now super small in the editor.  I tried to change the font by going to menu theme ctrl click line 17 with no luck.

**Comment by maestrith** [comment]
Try All+M Reset Zoom {Enter}

**Comment by pmcmillan99** [comment]
Thanks.  Did the trick.

**Comment by maestrith** [comment]
> Thanks. Did the trick.

👍
