### ISSUE TITLE
AHK-Studio error at first start

### ISSUE THREAD

**Issue by spuseldange** [maestrith/AHK-Studio#215]
Hi,
I want to try the AHK-Studio.
AHK portable on windows 7 language GB
AHK-Studio directory from zip copied  to the AHK directory.
At start up error at line 10, Picture of the error attached.
I hope You can help,
Martin

![Capture](https://user-images.githubusercontent.com/62953013/78053772-5d35be00-7381-11ea-809a-d876c064be61.JPG)

**Comment by maestrith** [comment]
Not really sure what's going on but if I had to guess that you might need to update AutoHotkey.  I've not tested AHK-Studio on anything other than an actual install of AutoHotkey so I'm going to guess that it won't.

**Comment by spuseldange** [comment]
Hi,
Right guess! Old version 1.0.48.05 on my PC.
Updated to v1.1.32.00. All fine now, AHK-Studio starts.
Thanks a lot and stay healthy,
Martin
