### ISSUE TITLE
If windows inside AHK Studio are moved, all windows of the application become intangible and error is thrown on next start

### ISSUE THREAD

**Issue by Gewerd-Strauss** [maestrith/AHK-Studio#231]
Hello maestrith,

I've now encountered the problem I've mentioned [in my last reply on the issue of "Notify"](https://github.com/maestrith/Notify/issues/2#issuecomment-808354656). 
The exact error message is displayed below

![WhatsApp Image 2021-03-27 at 10 28 12](https://user-images.githubusercontent.com/80548781/112716527-31dba580-8ee7-11eb-928e-9bdcee5b555a.jpeg)
Some context now: I usually split my Editor window into two, next to each other, just to have a second file to look up code. Below that, the debug window is located, below which the notes window is located. This is a bad description, so here is a screenshot: https://drive.google.com/file/d/1Q3msT9tTaxHONOihzduWm8yT8M_2qwtq/view?usp=sharing

Now, if one wants to resize the width of the two file-editing windows above the debug window**, it can happen that afterwards, the line to grab both windows becomes intangible. One can then not resize these windows anymore. If one then restarts AHK Studio***, an error is thrown (I think regarding scilexer, but I will give an update containing a direct screenshot once it happens again). Afterwards, it becomes impossible to launch this version of AHK Studio. one cannot replace the ahk-file itself, one cannot replace the scilexer file itself. The only method I have found is to do a complete reinstall of ahk-studio, by removing the entire folder and unzipping the downloaded zip again.

Thank you,
~Gw

**Comment by maestrith** [comment]
This is caused by an error in the Lib\gui.xml file.  There should be a history under Lib\XML Backup\Gui that can get you back up and running.  Choose the most recent and if you still get the error go back through the list.  If that still doesn't work sadly just delete the file Lib\gui.xml and it will return to stock

**Comment by Gewerd-Strauss** [comment]
Oh, good to know, thank you. I'll keep that in mind once it happens again. 
I assume I'll need to rename the backup to remove the timestring before I move it, right?
