### ISSUE TITLE
Some Unicode Characters are improperly rendered.

### ISSUE THREAD

**Issue by maestrith** [maestrith/AHK-Studio#24]
Not all, but some of the higher value ones do not show.
![2014-09-17_13-49-57](https://cloud.githubusercontent.com/assets/2114637/4308479/541296fa-3e93-11e4-862a-0f3bc521913d.png)

**Comment by Stamimail** [comment]
> So I guess AHK Studio will not work with Arabic or Hebrew :(
:(
I was trying Ctrl+Shift+N (#Include). 
The paths are retrived incorrctly.
There is also a problem with brackets characters like <>()... 
I get ) instead of (
even when the Keyboard Input is in English.

**Comment by Stamimail** [comment]
No sorry.
But the best you can do, is to have a copy of RTL VM for testing. Good also for future testing.

**Comment by maestrith** [comment]
RTL VM? I have never used it.  I'll have to look into it.  I am trying to think of why you would get a ) when you enter (... I am sorry that this is happening :(

**Comment by Stamimail** [comment]
I did so. It doesn't work.
[ ] works.
{}()<> is in the oppiste direction.

I have a "Windows XP Pro SP3 x86 Hebrew.vdi.rar" in Google Drive. Can it help you?

**Comment by maestrith** [comment]
sure, send me a message to maestrith@gmail.com
