### ISSUE TITLE
Permanent tooltip displays on file open

### ISSUE THREAD

**Issue by number1nub** [maestrith/AHK-Studio#27]
When opening a file, a tooltip is displayed for each of the files that is opened; the tooltip for the last file remains on screen until restarting studio. 

![capture](https://cloud.githubusercontent.com/assets/1151358/6036482/21e84a68-ac0b-11e4-9601-0b57f36d5c5d.PNG)

**Comment by maestrith** [comment]
I am going to have to see where that is.  Hopefully I can have that fixed soon.  Sorry :(

**Comment by maestrith** [comment]
Give it another go, It should be fixed.  Sorry about that.

**Comment by maestrith** [comment]
If it is fixed, go ahead and close it, or let me know and I will close it...I am still bad at this bug reporting system.

**Comment by maestrith** [comment]
Great! let me know if you find the program helpful.  I am always available for help.
