### ISSUE TITLE
Code Explorer organization

### ISSUE THREAD

**Issue by number1nub** [maestrith/AHK-Studio#28]
With multiple files open, the code explorer places the labels, functions, classes, etc. from all of the open files under every file in the explorer. In other words, every root item (file) in the code explorer has the same children, containing all matched items.

**Comment by maestrith** [comment]
1.0.42
Fixed: Reported by number1nub
-Code Explorer: This was one of the last things that I needed to update when I changed the entire backend for Code Explorer/Omni-Search
