### ISSUE TITLE
Plugin SDK

### ISSUE THREAD

**Issue by number1nub** [maestrith/AHK-Studio#29]
I'm curious if you have updated documentation on the current plugin SDK for studio?

I have multiple plugins that I had written some time ago using the style shown below, but they haven't seemed to work for a while now. Any help would be appreciated.

**Example old plugin (used to work):**
```ahk
addmenu("Enhanced Comment Line Toggle", A_ScriptFullPath)
hotkeys([1], {"NumpadSub": "EnhancedLineToggle"})

Enhanced_Comment_Line_Toggle()
{
	EnhancedLineToggle:
	sc := x.csc()
	sc.2078
	pi:=posinfo(), sl:=sc.2166(pi.start), el:=sc.2166(pi.end), end:=pi.end
	single := sl = el ? 1 : 0
	while, (sl <= el) {
		letter := sc.textrange(min := sc.2128(sl), min+3)		
		if (min > end && !single)
			break
		if (Trim(sc.textrange(min, sc.2136(sl))) = "") {
			sl++
			end--
			Continue
		}
		else if (letter = ";~ ") {	; Remove SciTE4AutoHotkey style comment
			sc.2190(min)
			sc.2192(min+3)
			sc.2194(0, "")
			end--
		}
		else if (SubStr(letter, 1, 1) = ";") {	; Remove a standard comment
			sc.2190(min)
			sc.2192(min+1)
			sc.2194(0, "")
			end--
		}
		else {	; Insert a comment symbol
			sc.2190(min)
			sc.2192(min)
			sc.2194(3, ";~ ")
			end++
		}
		sl++
	}
	sc.2079
	return
}
```

**Comment by maestrith** [comment]
I would love to have a chat with you and get your opinions on how I am going to makeover the plugin system.  If you like find me on Skype. I am maestrith on there I have been found by maestrith@gmail.com

**Comment by maestrith** [comment]
http://files.maestrith.com/AHK-Studio/Plugins/Geekdude%20Paste.ahk I have this plugin wrote in the new style but I have had it hand up before.

**Comment by number1nub** [comment]
I will definitely try to look you up and chat with you within the next couple days about some of these thoughts. I have been using studio for quite some time now and really like the direction you've been heading. Up until this point I've been relatively kept to myself about modifications and the issues I've had, but figured I'd start pitching in and help improved on this thing! you can find me at number1nub@gmail.com as well. Thanks for the responses, I wanted to just message you about things like this but now didn't have any other way to contact you. Will be in touch soon!

**Comment by maestrith** [comment]
I look forward to it :)

**Comment by maestrith** [comment]
With the new version of Studio I updated the way plugins worked.  I was having issues with things not properly updating and hanging up. http://files.maestrith.com/AHK-Studio/Plugins/Geekdude%20Paste.ahk that is a demo of how it should work from now on.  ;menu Name Of Menu,Special_Send

**Comment by maestrith** [comment]
https://github.com/maestrith/AHK-Studio/wiki/Plugin-SDK I wrote up a quick SDK.  Most of it you already know but not much has really changed.
