### ISSUE TITLE
Edit Comment Insert bug

### ISSUE THREAD

**Issue by number1nub** [maestrith/AHK-Studio#32]
In **Edit_Comment_Insert()** there are 2 issues:

- The line `settings.add2("comment","",insert)` doesn't seem to write the settings correctly to the settings file. This change makes it work correctly:

**Old:**
```ahk
insert:=RegExReplace(insert," ","%a_space%")
settings.add2("comment",,insert)
```
**Modified:**
```ahk
settings.add({path:"comment", text:RegExReplace(insert,"","%a_space%")})
```

- Debugging message box was left in at end of **Edit_Comment_Insert()**: `m(settings.ssn("//comment").text)` should be remove/commented.

Great updates, BTW! I really like the new object auto-completion feature!

**Comment by maestrith** [comment]
I seem to do that often don't I...Fixed add2() as well.

**Comment by maestrith** [comment]
Thanks :) I have been meaning to add the object auto-complete for a while I just keep getting distracted.
