### ISSUE TITLE
1.0.64 Breaks Omni Search and Code Explorer

### ISSUE THREAD

**Issue by number1nub** [maestrith/AHK-Studio#33]
The changes in 1.0.64 badly broke Code Explorer and Omni Search. 

Also, in **Edit_Comment_Insert**, should change the default InputBox value to `RegExReplace(format, "%a_space%", " ")` so that the %a_space% string doesn't show up in the input field.

**Comment by maestrith** [comment]
Good point! :)

**Comment by maestrith** [comment]
Should be good...I am going to look into that code explorer error.
