### ISSUE TITLE
Unregistered window class: specifically Scintilla

### ISSUE THREAD

**Issue by xhevahir** [maestrith/AHK-Studio#44]
I keep getting this error when I run AHK-Studio.exe, both with the git version and with the one linked to in the ahkscript.org discussion thread: "Unregistered window class: specifically Scintilla." (Somebody in the thread mentioned that putting SciLexer.dll in the folder fixed this, but it's not working for me.)

**Comment by maestrith** [comment]
not too sure where you are getting an exe for the program but I don't think I have a recent build compiled.  Try to download the most recent version and run it un-compiled.

**Comment by xhevahir** [comment]
I don't know why I didn't try running it uncompiled before, but it worked. Thanks.

**Comment by maestrith** [comment]
No problem :) Hope it works well for you.
