### ISSUE TITLE
Feature: Add a close button and some navigation buttons. Similar to notepad++

### ISSUE THREAD

**Issue by noticz** [maestrith/AHK-Studio#46]
Not sure if it is just my AHKS but there is no 'close project' item in the file menu. Either way I think there should be a menu item for 'close project' and close and navigate buttons at the top.
![ahks-feature-close](https://cloud.githubusercontent.com/assets/11874318/11751212/5a40796a-9ff5-11e5-9493-c2950efc600f.gif)

**Comment by maestrith** [comment]
Sorry :( I can not do that :(  You can always add the items "Close" "Next File" and "Previous File" to your toolbar.
