### ISSUE TITLE
® symbols break the "RemoveSpacesFromAroundCommas" function

### ISSUE THREAD

**Issue by lw1990** [maestrith/AHK-Studio#48]
if you have ® symbols, or other special symbols I'm sure, and use the "RemoveSpacesFromAroundCommas" function then it replaces the symbols with garbled text

**Comment by lw1990** [comment]
Force UTF8 doesn't fix this issue, thought maybe it would just letting you know :-)

**Comment by maestrith** [comment]
nope :) goto Download Plugins and if it is not pre-selected, select Add Spaces and download it
