### ISSUE TITLE
Caret Line Background theme option changes the text color

### ISSUE THREAD

**Issue by lw1990** [maestrith/AHK-Studio#50]
Alt+M > Theme
Changing the Caret Line Background, which I expected to only change the Current Line Background color, changes the text color of the main text

I was able to get it working by just resetting the theme and the caret line background seemed to stay changed, but it took 3 iterations to get it to play nice

**Comment by maestrith** [comment]
I never really tried it.  Let me give it a go

**Comment by maestrith** [comment]
I changed the alpha channel of the background color so it doesn't overpower the main text so much

**Comment by lw1990** [comment]
I updated and see what you did, please change it back because that's not the issue
Whatever color we specify for the background highlight even if it's strong should be accurate
The problem is that the main TEXT color changes once you change the Caret Line Background color. The caret line background color is working 100% perfect, except it is doing more than it should by also changing the text color.
I made a video to show this:
http://i.imgur.com/UEXsj7q.gifv
