### ISSUE TITLE
Feature: Add a save dialog on close if the file has been modified

### ISSUE THREAD

**Issue by noticz** [maestrith/AHK-Studio#54]
Common practice dialog if the file has been modified and you are closing the script and or program have it ask if you would like to save or cancel.

![ahks-save-dialog](https://cloud.githubusercontent.com/assets/11874318/11845460/44f34058-a3d1-11e5-9458-252c0228051d.gif)

**Comment by maestrith** [comment]
There is an option called Disable AutoSave.  This will cause that to be displayed....I have had that in there for a while now.

**Comment by noticz** [comment]
Make sense, marking this as closed.
