### ISSUE TITLE
Bug: When clicking menu item FTP Servers there is an error

### ISSUE THREAD

**Issue by noticz** [maestrith/AHK-Studio#55]
Probably an error on my part due to the fact that I have no FTP servers setup but figured I would at least put it here so you know of the error.

![ahks-ftp-menu-error](https://cloud.githubusercontent.com/assets/11874318/11847617/992c3c56-a3db-11e5-9073-62247dead3cc.gif)

**Comment by maestrith** [comment]
I had a menu item miss-labeled.  Should be fixed
