### ISSUE TITLE
Scintilla window creation and sizing

### ISSUE THREAD

**Issue by Treyin** [maestrith/AHK-Studio#58]
1. Right click Project Explorer item to get an option to open it in a new Scintilla window. 
2. Ability to resize Scintilla windows
![scintilla feature request](https://cloud.githubusercontent.com/assets/16631182/12220426/0a3fb1ae-b726-11e5-9fd7-1aa769747aa4.gif)

**Comment by maestrith** [comment]
yea, unfortunately the dragging of windows like that for the Scintilla windows probably won't be happening. Not that I haven't spent several hundred (literally) hours trying.  I will definitely keep my eyes open for some code for it, but for now I can not :( I am sorry.  I may at some point be able to do a separate window with a size adjustment but there are so many timing issues when it comes to AHK and Scintilla it just isn't possible :(

**Comment by maestrith** [comment]
I am open to suggestions on how to have re-sizable areas.  I am at a loss at the moment :(

**Comment by Treyin** [comment]
When you create a second Scintilla window, what keyword can I use to find out how that is initiated and follow the rabbit, so to speak?

What problems do you have with it? Briefly, what have you tried changing and what do you mean by timing issues?

**Comment by maestrith** [comment]
I'm still working on a descent solution.

**Comment by maestrith** [comment]
http://p.ahkscript.org/?p=e2680712 it's not perfect, but it's about as close as I can get.

**Comment by maestrith** [comment]
http://p.ahkscript.org/?p=c87bbc0e
