### ISSUE TITLE
Project Task Pad window

### ISSUE THREAD

**Issue by Treyin** [maestrith/AHK-Studio#59]
On large projects I frequent have to update multiple files to accomplish a single task. Often when I am doing this I notice something that needs to be changed. After finishing the new thing a few minutes later, I forgot the main task I was trying to undertake. 

What I've taken to doing is having notepad open and letting it serve as my Task Pad. This way I can write down what I'm trying to do, and when I inevitably find some code that needs tweaking I can write that down in the Task Pad and either do it later or immediately. When done in another window, it starts to get lost among all the other windows I have open. Regardless, I am able to keep track of my tasks much better and be more efficient.

It needn't be a big text area. I was thinking it would go nicely at the bottom left or right of the screen and have the same width as the Explorer windows.

**Comment by maestrith** [comment]
I don't know if this would be helpful, but each project has a notes file that you can use with it.  By default it is Ctrl+Alt+N

**Comment by Treyin** [comment]
Yes the notes work, just had to restructure my projects into one. I still have a Task pad sitting on top of the bottom right because I'm difficult and have ADD.

Thank you for showing helping me today!
