### ISSUE TITLE
Clipboard History window

### ISSUE THREAD

**Issue by Treyin** [maestrith/AHK-Studio#60]
I often copy blocks of text for use in many other places. Once pasted, I frequently have to customize it just a bit before I move on to the next place where I need to use the copied text. When customizing, I have to be mindful to NOT copy/paste any of the tweak text or else I lose my clipboard data. Sometimes I forget or just have to put something new on the clipboard.

Would it be possible to have a clipboard history window that showed the first line of text from each clipboard entry, truncated so that there is no text wrapping? So each line would be the text from a different clipboard entry. Then, hopefully, all someone would have to do is click on the clipboard history line they want to load it back into their clipboard?

Again, it needn't be a big area, just the size of the Explorer area would suffice.

Sorry, I hope I'm not being annoying. I'm just putting my thoughts out there for you to reject if you see fit. Or, I guess I could try delving into your code and seeing if I could make the change, but I'd appreciate a pointer in the correct direction, of course!

**Comment by maestrith** [comment]
In the past I had a bit of an issue with a clipboard history but I can try to think of something.

**Comment by maestrith** [comment]
Added:
-Clipboard History: Options/Clipboard History to enable it, then Display Clipboard History to have Omni show it ")" for prefix
