### ISSUE TITLE
While

### ISSUE THREAD

**Issue by Treyin** [maestrith/AHK-Studio#61]

**Comment by Treyin** [comment]
![image](https://cloud.githubusercontent.com/assets/16631182/12224091/11eb6ea8-b79d-11e5-8e14-c6906178912c.png)

**Comment by maestrith** [comment]
lol ok

**Comment by Treyin** [comment]
Sorry, The text that I typed didn't show up for some reason! Yeah, the While shouldn't be there on the right. :)

**Comment by maestrith** [comment]
I think the most recent update should have addressed this issue.  Let me know if it didn't

**Comment by Treyin** [comment]
I'm still getting 1.022.2 as the latest, and here's a screenshot. See screenshot, brackets are fine, my while statements are indeed within the methods.

![image](https://cloud.githubusercontent.com/assets/16631182/12238000/78c9763a-b836-11e5-92b6-cfa0ca517883.png)

**Comment by maestrith** [comment]
OH! duh...was thinking another thing...ok

**Comment by maestrith** [comment]
I fixed functions that would be named while, but not methods. Updated.

**Comment by Treyin** [comment]
Fixed. Thank you! I actually find the code explorer very handy while synchronizing complimentary class code.
