### ISSUE TITLE
Refreshing plugins or trying to download a new plugin will kill your separators in the menu

### ISSUE THREAD

**Issue by noticz** [maestrith/AHK-Studio#62]
Here is the problem...
![2016-01-13_18-14-24](https://cloud.githubusercontent.com/assets/11874318/12313070/b861b3a6-ba21-11e5-8011-1f250e14de08.gif)

**Comment by maestrith** [comment]
do they come back when you restart Studio?

**Comment by noticz** [comment]
No, which is why I always keep a backup of the menus.XML and have to revert
back to it.

**Comment by maestrith** [comment]
ok, so is it just the separateors in the plugins menu or across all menus? sorry I can't really see too well on the gif.

**Comment by noticz** [comment]
Everything except one that is still shown in the file menu. All the other
disappeared and dont show up. Not sure if it is something in the menus.XML
file that I made but it is possible.

**Comment by maestrith** [comment]
ok, not 100% sure.  I will have to check.

**Comment by maestrith** [comment]
![capture](https://cloud.githubusercontent.com/assets/2114637/12317045/1c586952-ba5b-11e5-9330-3aa4979a8800.gif)

**Comment by maestrith** [comment]
so is it only when you do the refresh plugins? or do you have to download a plugin to make it go funny?

**Comment by maestrith** [comment]
also send me a copy of your menus.xml so I can test it on my machine.  Also make sure you are on the most recent version...I know I did do some updates not too long ago

**Comment by noticz** [comment]
http://whitegauges.net/temp/ahk-studios/menus_backup.xml

**Comment by maestrith** [comment]
Thanks, I will look at it here in a bit.

**Comment by noticz** [comment]
This feature was fixed with an update, thanks maestrith
