### ISSUE TITLE
Right panel not showing subclasses

### ISSUE THREAD

**Issue by KaoSDlanor** [maestrith/AHK-Studio#63]
Please see below image

![image](https://cloud.githubusercontent.com/assets/2821154/12550817/d297baf8-c36e-11e5-9389-ad7c73d71b3e.png)

**Comment by maestrith** [comment]
You are correct, I have not addressed the sub-classes.  I will do my best but I can not make any promises to get them in properly.  I am in the middle of a major update that has been taking up all of my time for the past 2 weeks (see the Alpha branch if interested)

**Comment by KaoSDlanor** [comment]
no issues. I barely use the right pane but figured you may want to know

**Comment by maestrith** [comment]
LOL! oh it is a known thing...I just
1. Dislike the Code Explorer.  It is a waste of time IMO.  I can get to everything that it includes through the Omni-Search but there are those who still use it so I leave it in.
2. The amount of programming that is involved with getting sub-classes to properly work is a nightmare.  I can try it but that is something that is going to be WAY down the road.  It took forever to figure out how to split up the code into functions/methods without them getting in each others way.  I will try to mess with it but man...that's going to be 8-100 hours that I really am not looking forward to.  If you can figure out a way to make it work please let me know, but it has to be able to take into account all the functions/classes/everything else that Studio tracks at the same time while trying to take into account the different styles that AHK allows us to use.

**Comment by noticz** [comment]
Post this issue on the forum and I bet someone can come up with something without Maestrith . I know he would toss it in if the community would pitch in for sure. I tell you, ahk-studios has been a life saver...the project explorer alone saves me so much time.

**Comment by maestrith** [comment]
the issue with the sub-classes is not as simple to do...I had a hard enough time getting simple classes to actually work and adding in classes within classes only makes it that much more difficult.  I will try to put some thought into it but at this current time I really can not think of a good solution. :(

**Comment by maestrith** [comment]
This issue should have been fixed a while ago, I just forgot to close it.
