### ISSUE TITLE
indent lost after pressing enter [1.002.35]

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#66]
press enter to autocomplete then indentation is lost
![bug](https://cloud.githubusercontent.com/assets/17204819/14561044/f9369e92-0313-11e6-86ee-592f9c034e40.gif)

**Comment by noticz** [comment]
I had this same issue and if I am not mistaken I think it ended up being one of two things under the menu:
Options->Formatting Options->Manual Continuation Line
Options->Program Options->Auto Advance

Give a look, I have both of the above checked.

**Comment by maestrith** [comment]
Sadly there is an option called Full Auto you can find it and disable it by doing:

Alt+M then type in full auto into the box that comes up and then press enter.
