### ISSUE TITLE
Untitled.ahk created after save as

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#67]
in project explorer close all but project1.ahk
now save as project2.ahk
-> project explorer lists now project2.ahk & Untitled.ahk

**Comment by maestrith** [comment]
Thank you for the bug report.  I have been having some issues with an IRL project (non-ahk) that has been taking much of my viable brain cycles and when I actually get some time to lay down and look at things, everything looks like a jumbled mess.  I will be looking into this and the other issue very soon.
