### ISSUE TITLE
Quick Find bar

### ISSUE THREAD

**Issue by lw1990** [maestrith/AHK-Studio#68]
Just checking in on this editor since Sublime and Scite4Ahk still drive me nuts
It's looking like a ton better than the last time I used it, cleaned it up very well!

One thing that bugged me was this:

![image](https://cloud.githubusercontent.com/assets/2457611/14760197/e574dc78-090a-11e6-8d74-43f164c09766.png)

Quick find bar should have white or grey background and not be creeping into the other panel's space. Also the checkboxes need more padding on top

But really it looks 1000x better than last year

**Comment by maestrith** [comment]
In the theme window you can change the foreground/background colors of the Quick Find to whatever you like (also depending on top or bottom as well).  What OS are you running?  I have had some issues with positioning but I thought I had it solved.

**Comment by lw1990** [comment]
Windows 10
Here's a screenshot of sublime and scite's find bar (should use it for default UI inspiration even if it doesn't have as many AHK features)

![image](https://cloud.githubusercontent.com/assets/2457611/14764067/0beaff28-0978-11e6-84b4-9931c797c381.png)


Also, plugin updates didn't work for me for the "remove spaces around commas" thing, and there seems to be two different remove commas thing that do the same thing, but one is a remnant of the past, but that's no big deal
