### ISSUE TITLE
Line numbers not visible

### ISSUE THREAD

**Issue by lw1990** [maestrith/AHK-Studio#69]
![image](https://cloud.githubusercontent.com/assets/2457611/14764777/fbac8738-0992-11e6-9b61-616e7bef3794.png)

Look closely at the line numbers. happens even if full screen.
Typical Windows 10 OS

**Comment by maestrith** [comment]
This is an issue that has been around for a while. It should clear itself up when you hit enter for the first time. I am in the middle of a very large update right now. Forgotten things but studio is not in a state where I feel comfortable updating it. I will keep this in mind for this rewrite.

**Comment by maestrith** [comment]
If this persists, you "should" be able to just hit enter in any line and the width of the line numbers should expand to show all of the text.
