### ISSUE TITLE
Can only run if compiled (scilexer.dll problem)

### ISSUE THREAD

**Issue by henrik-jensen** [maestrith/AHK-Studio#70]
IF I run the "AHK-Studio.ahk" script with the installed `AutoHotkeyU32.exe` I get this error message:

```
---------------------------
AHK-Studio.ahk
---------------------------
Error:  Unregistered window class.

Specifically: Scintilla

	Line#
	978: }
	979: if (!init)  
	980: DllCall("LoadLibrary","str","scilexer.dll"),init:=1  
	981: v.im:=info.main,v.ip:=info.pos,v.iw:=info.win,notify:=info.notify,win:=window?window:1,pos:=info.pos?info.pos:"x0 y0 w0 h0"  
	982: if (info.hide)  
	983: pos.=" Hide"  
	984: mask := 0x10000000|0x400000|0x40000000
--->	985: Gui,%win%:Add,custom,%pos% classScintilla +%mask% hwndsc g%notify%
	986: For a,b in {fn:2184,ptr:2185}
	987: this[a]:=DllCall("SendMessageA",UInt,sc,int,b,int,0,int,0)  
	988: this.parent:=sc,this.sc:=sc,s.ctrl[sc]:=this,this.2660(1)  
	989: For a,b in [[2563,1],[2565,1],[2614,1],[2124,1],[2403,0x08,0],[2402,0x1|0x4,120]]
	990: this[b.1](b.2,b.3?b.3:0)  
	991: this.2403(15,20)  
	992: if (info.main)  

The current thread will exit.
---------------------------
OK   
---------------------------

```
Compiling to `AHK-Studio.exe` (With `AutoHotkeyU32.exe`) makes it work.
I wonder if the problem is that `SafeDllSearchMode` is enabled per default [MSDN Documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx).

Workarounds I found:
- As mentioned, Compile `AHK-Studio.ahk`.
- or copy the `scilexer.dll` to AutoHotkeys install directory (`c:\Program Files\AutoHotkey` in my case).
- or copy the installed `AutoHotkeyU32.exe` to the `AHK-Studio` folder where `scilexer.dll` resides and make a Shortcut to THIS particular exe and give `AHK-Studio.ahk` as parameter

My System:
Windows 7 64 bit
AutoHotKey: v1.1.23.06

**Comment by henrik-jensen** [comment]
Think I've solved it.
Seems LoadLibrary needs an absolute path otherwise it won't find the dll on my system.
I changed line 980 in AHK-Studio.ahk:
```
			DllCall("LoadLibrary","str","scilexer.dll"),init:=1
```
To this:
```
			DllCall("LoadLibrary","str", A_ScriptDir "\scilexer.dll"),init:=1
```

Here is the patch `absolute_path.diff`:
```
diff --git a/AHK-Studio.ahk b/AHK-Studio.ahk
index 95f3050..407acf5 100644
--- a/AHK-Studio.ahk
+++ b/AHK-Studio.ahk
@@ -977,7 +977,7 @@ class s{
 			return sc
 		}
 		if(!init)
-			DllCall("LoadLibrary","str","scilexer.dll"),init:=1
+			DllCall("LoadLibrary","str", A_ScriptDir "\scilexer.dll"),init:=1
 		v.im:=info.main,v.ip:=info.pos,v.iw:=info.win,notify:=info.notify,win:=window?window:1,pos:=info.pos?info.pos:"x0 y0 w0 h0"
 		if(info.hide)
 			pos.=" Hide"

```

I wonder if others who don't have this problem actually has a `SciLexer.dll` that gets picked up somewhere in the one of the default search directories according to [MSDN docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#standard_search_order_for_desktop_applications) ?

**Comment by maestrith** [comment]
Thanks for the report.  I have not had anyone report this as an issue but I will update it on my side for the next update (which will be an absolutely massive update) at least for me. I am not real sure why that would happen because I set the working directory to SetWorkingDir,%A_ScriptDir% on line 3 and that "should" take care of all of that.

**Comment by henrik-jensen** [comment]
Thanks for the reply.
It is probably only my system (Win7 64 bit) that is strange, especially considering no one else has reported this as a problem. But if the problem is that LoadLibrary needs an absolute path then %A_ScriptDir% on top won't change that. LoadLibrary still gets an relative path unless %A_ScriptDir% is put explicit in front of `SciLexer.dll`.
I still wonder, though the chances are tiny considering the none-existing issue reports,  if some other `SciLexer.dll` gets picked up either from disk or already in memory when people are running AHKStudio as a script.

A way to test this, for anyone who might find the time, would be to rename `SciLexer.dll` to, say, `SciLexer_AHKStudio.dll`, and change line 980 to reflect that
```
DllCall("LoadLibrary","str","SciLexer_AHKStudio.dll"),init:=1
```
and then see if it still runs. If not, that could indicate that some other `SciLexer.dll` gets used when the original is run and now it can't find `SciLexer_AHKStudio.dll`.
(And check that [`SafeDllSearchMode`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#standard_search_order_for_desktop_applications) is not disable, though it should'nt be per default)

**Comment by maestrith** [comment]
I really wish there was a way to PM people here.  I would like to chat on Skype if you have it.  Just look for maestrith.

**Comment by henrik-jensen** [comment]
Oh Sorry, I don't have skype but my email is this (spammer protected :-) :
FirstName := "henrik"
Dot := "."
LastName := "jensen0" ;that's a zero at the end
GmailServer := "@gmail.com" 
email := FirstName Dot LastName GmailServer

Or I could create an account on the autohotkey.com forum ( the do have PMs right ?)

**Comment by jvr-ks** [comment]
I think "SciLexer.dll" is only 32 bit compatible.
If you use the context menu "Run Script" on 64 bit Windows, it uses the 32 bit Autohotkey version!
