### ISSUE TITLE
Plugin download does not work

### ISSUE THREAD

**Issue by evilC** [maestrith/AHK-Studio#72]
When downloading a plugin, if you tick a plugin and then click "Download Checked", the plugin is not installed.
A dialog is presented which says:

```Installation Report:  ```
```Debug Current Script - ```

Looking at the code, in `Download_Plugins`, at the `dpdl:` label, the following like does not seem to be doing anything useful: (Line 2208 for me):
`while,num:=LV_GetNext(0,"C"){`
num does not get assigned a value.

**Comment by evilC** [comment]
ah, hmm, maybe I cannot debug AHKStudio with Scite?
When I output the value of num in a msgbox, it was 15. But if I set a breakpoint there in scite, i cannot inspect the value of num.

So to clarify, num DOES have a value.

**Comment by maestrith** [comment]
oh you are working with debugging :( I really need to work on that.  I would be interested to get some ideas from you for improvements going forward

**Comment by evilC** [comment]
Thanks for your time tonight...
I think that debugging should be enabled by default. If you are installing something like AHKStudio, then having debugging working out-of-the-box is a must IMHO.
Also I would default to traditional keys. so F5 is "play" - if you have enabled debugging, then it should go to the first breakpoint (No need for second hotkey).
Then your usual F10/F11 step in/over.
Toolbar icons would also be a plus.
The output window should be free of superfluous information (Or the current window we used to debug the debugger should be another window, which is hidden by default) - in normal usage, only `outputdebug` messages and warnings / errors etc should be displayed here.
Had some issues with the other stuff you showed me also, but as you say, you are working on the new branch. Will have more of a play and probably skype you tomorrow or something.

**Comment by maestrith** [comment]
Hopefully all the work that I have done has fixed this issue?
