### ISSUE TITLE
Code Explorer: Clicking top level doesn't display AHK code

### ISSUE THREAD

**Issue by Graushwein** [maestrith/AHK-Studio#73]
Clicking on the filename in the Code Explorer should show the same file as when you click on the top level in the Project Explorer.

(Also: The Code Explorer is a very useful feature for me. Thank you so much for it! It is an easy way to see the Class methods. Is there a setting to make it so that clicking on a plus sign doesn't load the code into the active Scintilla window? I frequently forget all the method names and need look them up in the Code Explorer, which changes the focus to the other class file. Then when I go back to the file it doesn't go back to the same spot, so I have to find where i was again.)

![image](https://cloud.githubusercontent.com/assets/16631182/17080288/664e89dc-50de-11e6-9594-f289cb8107a4.png)

**Comment by maestrith** [comment]
The filename in the Code Explorer is a placeholder to show that the information below belongs to that Project not that it is an indicator of that file, so clicking on it will not change your focus to that file.  You can use Alt+J <part of filename you want to jump to>{enter} to quickly jump to your files and Alt+J will automatically show only the main project/s that are open to quickly get to the main file.
