### ISSUE TITLE
Can't remove control window or resize windows

### ISSUE THREAD

**Issue by Graushwein** [maestrith/AHK-Studio#74]
Step by step:
I had just upgraded to 3.0, (from 1.002.39) which didn't upgrade with my old window layout and wasn't a big deal. (It just showed a single window with my recently open code.)
Right clicked only window, Split Control > Left (Probably didn't select Control Type)
Right clicked left window, Split Control > Bottom  (Probably didn't select Control Type)
Right clicked left-bottom window, Control Type > Project Explorer
Right clicked left-top window, Control Type > Code Explorer
Right clicked left-top window, Split Control > Bottom (A black space between left windows appeared and I think I could no longer resize windows by click-dragging edges. It was actually the Quick-Find bar but no text I think.)
Right clicked black space between left windows and selected Move To Bottom (realizing that was the Quick-Find bar)
Probably would have gotten error had I tried to close a left control, but moved Quick find to top instead with Right Click > Move to top
Right clicked left-top window to Remove Control and got image below
(I can no longer resize windows regardless of whether the Quick Find is at top or bottom)

And for some reason resizing windows stops working/allowing them to be resized. Sometimes I'll move it a bit and it'll stop after a few times. Once, it just sat open for and hour and then couldn't resize. Another time, trying to investigate, I clicked like crazy on one of the dividers and it broke too, but it didn't happen a second time.

(Also I find it odd that the default settings for Move Selected Word Left/Right use Shift+Alt, but Up/Down use Shift+Cntrl? I know I can change it.)

(Don't worry, I'm pretty sure I know how to fix it.)

![image](https://cloud.githubusercontent.com/assets/16631182/17079746/6675d10a-50ce-11e6-8271-be73e4cc7bd1.png)

Tried moving windows around with right click to fix it, but couldn't. Closed Studio and got error below.

![image](https://cloud.githubusercontent.com/assets/16631182/17080090/48a3bf5c-50d8-11e6-93b9-a602c2c803a7.png)

Tried moving everything around to fix it via interface, but it wouldn't work. Here is the GUI.xml:
`<?xml version="1.0"?>
<gui>
	<controls win="1">
		<control hwnd="2100894" parent="2100894" type="Project Explorer" lp="0.0000000000" tp="0.7195571956" file="C:\Users\Chris\AppData\Local\MacroLab\Eve Pilot\Scripts\Development\eve_assist\InventoryMgr.ahk" b="813" l="0" r="216" t="585" ra="461290" ta="15270812" h="0" w="0" x="" y=""></control>
		<control hwnd="2822998" parent="2822998" type="Code Explorer" lp="0.0000000000" tp="0.0000000000" file="C:\Users\Chris\AppData\Local\MacroLab\Eve Pilot\Scripts\Development\eve_assist\InventoryMgr.ahk" b="342" l="0" r="216" t="0" ba="15270812" ra="461290" h="0" w="0" x="" y=""></control>
		<control hwnd="461290" parent="461290" type="Scintilla" lp="0.1350000000" tp="0.0000000000" file="C:\Users\Chris\AppData\Local\MacroLab\Eve Pilot\Scripts\Development\eve_assist\MiningDronesV2.1.ahk" b="813" l="216" r="1600" t="0" la="2822998" h="0" w="0" x="" y=""></control>
		<control hwnd="15270812" parent="15270812" type="Tracked Notes" lp="0.0000000000" tp="0.4206642066" file="C:\Users\Chris\AppData\Local\MacroLab\Eve Pilot\Scripts\Development\eve_assist\InventoryMgr.ahk" b="585" l="0" r="216" t="342" win="Tracked_Notes" ba="2100894" ra="461290" ta="2822998" h="0" w="0" x="" y=""></control></controls>
	<win win="1" max="1" pos="x-8 y-8 w1600 h857">
		<control hwnd="2167254" type="Scintilla" h="834" w="1183" x="417" y="-21" file="C:\Users\Chris\AppData\Local\MacroLab\Eve Pilot\Scripts\Development\eve_assist\InventoryMgr.ahk" lp="0.260625" tp="-0.025862"></control>
		<control hwnd="854506" type="Tracked Notes" h="813" w="417" x="0" y="21" Scintilla="4656374" TreeView="15993608" ra="2167254"></control>
		<control hwnd="854506" type="Code Explorer" h="834" w="417" x="0" y="-21" ra="2167254" tp="-0.025862"></control></win>
	<win win="Tracked_Notes"><control type="Scintilla" hwnd="4656374" h="813" w="334" x="83" y="0"></control>
		<control type="TreeView" hwnd="15993608" h="813" w="83" x="0" y="0"></control></win>
</gui>`

Deleted GUI and restarted Studio, all is working fine.

**Comment by maestrith** [comment]
I tried to reproduce this and was unable.  If it happens again let me know, and if you could reproduce this regularly I would love to see an animated gif or video showing what happened so that I can do exactly what you are to reproduce it so I can fix it.
