### ISSUE TITLE
AHK studio keeps deleting all the lines in my #Include files for no reason!!! 

### ISSUE THREAD

**Issue by Graushwein** [maestrith/AHK-Studio#75]
It isn't even backing them up first, so I'm losing work. It happens randomly, probably when I save changes, which I do often.

The only thing that I can imagine might contribute is that I have two projects I'm working on that use the same #Include files. That and some Includes have their own Includes?

**Comment by maestrith** [comment]
Is there a way that we can chat?  I would like to be able to setup my version of Studio as close to yours as possible and I want to get everything I can to see what is going on.

**Comment by Graushwein** [comment]
I had gone back to using an old version because the newer version is is double-pasting. Using the new one now to see if the new one does it.
[AHK Studio Copy.zip](https://github.com/maestrith/AHK-Studio/files/389139/AHK.Studio.Copy.zip)

**Comment by maestrith** [comment]
I was more referring to having the files that you are editing, what files are open, so that I can see what is going on and reproduce the error on my side so it can be fixed.

**Comment by Graushwein** [comment]
I know this happened on 2.37, but I've just started a 1.003.2 clean slate, gonna see if it keeps happening. I'll come back in a few days to report.
Basically, I have 2+ projects (AHK files) open at the same time, where each has the same 10+ Includes at the bottom. I go back and forth between the top project files updating code, often updating the Include files from either project. Sometimes I'll go to an include and every line is gone, and there was no backup made with the recent changes. I've had other times where all but one include file was made blank. One of the projects will show the file with all the lines, but the other shows it as empty. The empty one is correct because notepad brings it up blank.

If it happens any more I'll share my code here with you.

**Comment by Graushwein** [comment]
[MyProjects.zip](https://github.com/maestrith/AHK-Studio/files/394977/MyProjects.zip)
Yep, it just happened again. I had the three projects open and was just browsing around in them back and forth.
As you can see in the video, I can get it to happen 100% of the time by using CodeExplorer. But sometimes I can just close a project as soon as I put the 3 in there and it will happen. Studio doesn't backup the files before they are cleaned out either.
[https://youtu.be/9oX6TSaEy-A](url)
[https://youtu.be/ltIaVwQVIcw](url)

Setup: Left-Top (CodeExplorer), Left-Bottom (ProjectExplorer), Right (CodeWindow)
Put 3 projects into Studio (single drag alphabetically)
In CodeExplorer, use the plus to Expand BookmarkBelt's Class section and then click on Class...Window
In ProjectExplorer, scroll (but don't click yet) so you can see on .....Manager (Your focus is still on BookmarkBelt's Class...Window)
Right Click on .....Manager and choose Close
[End of steps]

To Verify: expand BookmarkCan in the ProjectExplorer and click on each file to see which ones are blank.
The files are not blank yet, though. They would become blank if you save, and they don't get backed up either.

**Comment by Graushwein** [comment]
Bump.

**Comment by maestrith** [comment]
Sorry, I have had a crazy week.  My father fell and hurt his leg and we had to go to the hospital to get x-rays and I have been in a lot of pain thanks to my injury... I also have been working on my PC to get it back to where it was and I have not even thought about programming.  I will look into your videos...Please give me some time.

**Comment by maestrith** [comment]
I have taken a look at the videos and honestly you are not explaining anything, you just show a few files (which I have asked in the past for a file list so I can actually understand what files were being effected and you have not provided the list yet) and you go so fast without saying a word and I really can not follow it so it makes things REALLY hard for me to follow.  So from what I gather you have a lot of files that contain the same includes, you close one of the files and it clears out the data from those include files.  This would have been so much easier if you had sent me the projects so I could see it on my computer.  I think I may know what is going on but having a file list (which I asked for a while ago) would have helped me much more than a couple videos.

**Comment by maestrith** [comment]
I tried to setup 2 basic projects with the same includes, close 1 and have it mess up the other.  I could not get it to do this.  What I need from you before I will go any further is.
1. A zip file with all of the files that you have shown in the 2 videos so that I can open them on my system and have it re-produce the issue so that I can see it for myself.
2. Once you have provided me with the files, at least a few days so that I can figure it out.

**Comment by Graushwein** [comment]
I understand. I posted myprojects.zip above.

**Comment by maestrith** [comment]
oh crap...I am sorry.  Man I am missing things.....

**Comment by maestrith** [comment]
I made a couple changes and tried to reproduce on my system and from what I tried I could not get it to reproduce the error.  Give it an update and see if it fixes the issue.  If not we are going to have to do a TeamViewer or Skype session so I can see on your system what's up and do some troubleshooting.  Hopefully I have it sorted but I suppose time will tell.

**Comment by Graushwein** [comment]
Thank you so much. I'm now unable to replicate the error with the new version. I'm going to close this. If I encounter it again I'll just reopen it.
