### ISSUE TITLE
Global and Super-Global variables not shown in Variable Browser

### ISSUE THREAD

**Issue by evilC** [maestrith/AHK-Studio#81]
With the following code snippets, g is never shown in the variable browser

```
g := 123
test()

test(){
	global g
	a := 1	 ;*[test]
}
```

```
global g := 123
test()

test(){
	a := 1	 ;*[test]
}
```

**Comment by maestrith** [comment]
I can not fix this.  This is the fault of the debugger in AHK_H which I can not solve.  Please close this.

**Comment by evilC** [comment]
I raised this from work, but I guess I must have been running AHK_H at work also. I thought I was on L, but I could well have swapped my EXE for H and forgot about it.  
Will verify at work tomorrow that this was all that it was.
