### ISSUE TITLE
Objects not showing contents in Variable Browser

### ISSUE THREAD

**Issue by evilC** [maestrith/AHK-Studio#82]
In the following code, a and b both show as empty in the variable browser
```
mc := new myclass()
test()

class myclass {
	__New(){
		a := {hello: "world"} ;*[test]
	}
}

test(){
	b := {hello: "world"} ;*[test]
}
```

**Comment by evilC** [comment]
In fact, on my work PC, the variable browser is totally non-functional.

This is a fresh install.  
Not sure if the debugging plugin is actually installed or not - when I try to download it, I get:
![image](http://i.imgur.com/D8HvItN.png)

I can start debugging, step in etc, so I guess debugging is installed?

**Comment by maestrith** [comment]
Debugging has not been a plugin for a while now.  I wrote it into the main script
![autohotkey_2016-09-25_10-53-04](https://cloud.githubusercontent.com/assets/2114637/18816029/5c6d4b1c-830e-11e6-966e-5956273886d8.png)
