### ISSUE TITLE
Breakpoints not being hit in included files

### ISSUE THREAD

**Issue by evilC** [maestrith/AHK-Studio#83]
test.ahk
```
#include test2.ahk
test2()
```

test2.ahk
```
test2(){
   a := 1 ;*[test2]
}
```

Start debugging, the breakpoint is not hit.

**Comment by maestrith** [comment]
when this happens try to refresh the Code Explorer.  Sometimes data gets out of sync and needs refreshed.  This can be done from the Alt+M window.
