### ISSUE TITLE
Open Help File via F1 not working

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#88]
1) Create a new script then select anything or nothing in the first row, just make sure the cursor is in the first row, now press F1 to open the Help File, this will not work. 

2) Another thing I have noticed, double click on NoEnv will not select the complete command #NoEnv. (as in Scite4AHK)

3) pressing F1 then will not open the corresponding help section ( #NoEnv) . In Scite this works as expected, double click on a part of the command to select it completely then press F1 to open the help section.

I am not sure if this can be set somewhere in AHK Studio, but I believe Scite4AHK is behaving correctly (as expected).

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
issue # 1: fixed
issue # 2: fixed
issue # 3: partially fixed, there seems to be still an issue when a command is commented out. 
the corresponding help section is not found for ; #Warn
[![quirk8.gif](https://s22.postimg.org/80ar69x2p/quirk8.gif)](https://postimg.org/image/ri5em7u0d/)

**Comment by megabugman** [comment]
issue # 3: fixed
