### ISSUE TITLE
incorrect context menu / selection lost

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#89]
select a command eg by double click, then move the mouse and press the right mouse button.
- the selection is lost
- context menu commands like copy and paste are still available, but do not work

I've checked with other Scintilla based editors. Geany works like expected. No matter if the mouse position has changed the text remains selected and context commands like copy and paste still work.
This is imho the correct/expected way an editor should work (like notepad).

In AutoGUI the text selection is also lost, but context commands are grayed out, the same applies to Scite4AHK, though I would suggest to have it the notepad/geany way.

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
selection lost issue seems fixed.

but I found some other bugs
see [here](https://github.com/maestrith/AHK-Studio/issues/102)
and [here](https://github.com/maestrith/AHK-Studio/issues/103)

I'll create a new issue for the (un)greyed out context menu commands
