### ISSUE TITLE
Hotkeys issues

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#90]
- i noticed control + End does not work (cursor should jump to end)
- control + t seems to swap two rows, again i am not sure if this is a scintilla hotkey, but should it not be included in "display hotkeys" commands window? (or turned off, see below)
- control +r and control +e add some control characters DC2 and ENQ, 
not sure, but is it useful to have a shortcut for inserting such things? 
notepad2 at least turned these hotkeys off.

**Comment by maestrith** [comment]
Ctrl+R and Ctrl+E are default Scintilla control hotkeys :( I will have to figure out a way to filter them out but with the editable hotkeys this might be a problem.

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.
Although Ctrl+End will probably still not work.  Ctrl+End seems to work for me so I am guessing it has something to do with your keyboards language and AHK.  Not completely sure how to fix that but I am open to suggestions.

Ctrl+T is a built in Scintilla function

**Comment by megabugman** [comment]
Ctrl+R and Ctrl+E issue fixed.
Ctrl+End works.
