### ISSUE TITLE
Run Selected Text: An older instance of this script is already running Message

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#91]
1) when running this code `MsgBox, Hello` via "Run Selected Text" a message pops up: An older instance of this script is already running. running the same code via "Run Comment Block" after commenting it out (+F1) does not trigger the "another instance" message box. IMO the latter is the expected/correct behavior.

2) selecting and running this code
```
#SingleInstance Force
MsgBox, Hello
```
will also trigger the message

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
fixed
