### ISSUE TITLE
Another Run Selected Text Issue

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#92]
From the following code select only the first and third row via CTRL then run "Run Selected Text"
```
MsgBox, Hello 1
MsgBox, Hello 2
MsgBox, Hello 3
```
A single MessageBox pops up "Hello1MsgBox,Hello 3".
While I had expected to see two MessageBoxes.

If the second command is commented out, "Run Selected Text" works as expected.

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
fixed
