### ISSUE TITLE
Error: Failed attempt to launch program, Action: <plugins\Bookmarks.ahk mb>

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#93]
Run Tools/Bookmarks/Manage Bookmarks
A MessageBox pops up: "This requires a plugin that has not been downloaded yet, Download it now?
Press No. The Message appears "Unable to run this option", then "Unable to run the Error Message will come up.

The error applies to other plugins like code vault, run comment block or run selected text.

Trying to run a missing plugin after selected via Alt+M, then only "Unable to run this option" will pop up,
but no Error Window. I believe, that's how it should be.

**Comment by maestrith** [comment]
yea, I am re-writing a lot of the plugin functionality and some of the plugins will be removed.  Sorry you started using Studio while I am working on things :(

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
fixed
