### ISSUE TITLE
klick in menu search window resizes Scintilla Control

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#95]
guess I found another minor issue where pressing the mouse button in menu search window could resize the Scintilla Control.
[![quirk.gif](https://s11.postimg.org/5l3t5srz7/quirk.gif)](https://postimg.org/image/3tauaw8m7/)

**Comment by maestrith** [comment]
I can not re-create this issue.  I am not sure why it is happening but I will see if I can figure something out.

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
fixed
