### ISSUE TITLE
parameters not displayed in single line hotkey assignment

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#96]
when assigning a command to a hotkey directly, parameters are not displayed.
in another IDE this works as expected.
[![quirk2.png](https://s11.postimg.org/aupxuih43/quirk2.png)](https://postimg.org/image/mjtxih82n/)

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
fixed
