### ISSUE TITLE
context menu entry not grayed out

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#98]
add some text, then delete it, undo, redo.
now redo should be grayed out
[![quirk3.gif](https://s12.postimg.org/6huqw95rx/quirk3.gif)](https://postimg.org/image/f0470lcah/)
works as expected in other IDE
[![quirk4.gif](https://s11.postimg.org/95egmwcpf/quirk4.gif)](https://postimg.org/image/urth3xb9r/)

**Comment by maestrith** [comment]
Addressed in 1.003.13.  Please close this thread if it is fixed.

**Comment by megabugman** [comment]
as far as I see the issue has been fixed by hiding the Redo command from the context menu.
this is not the fix I had expected. rather than hiding the command should be greyed out like in any other
typical win application I know of. 

other commands like cut, paste

**Comment by maestrith** [comment]
yea, it's just easier to not have them in the menu because I am building the menu every time.  I'll see what I can do.

**Comment by maestrith** [comment]
Should be addressed in the latest 1.003.13

**Comment by megabugman** [comment]
now undo is broken. (greyed out, after deleting some text)

**Comment by maestrith** [comment]
LOL! Missed some (). Should be fixed

**Comment by megabugman** [comment]
yeah, works now. 
though I found another issue :)

ATM Open Folder Command in Context Menu does nothing (in a fresh/unsaved project) ergo should also be greyed out .

**Comment by maestrith** [comment]
ah ok

**Comment by maestrith** [comment]
updated.

**Comment by maestrith** [comment]
I rarely use the mouse and even less for most of what the menus do.  I usually keep my Studio to a main edit window and that's it so there are bound to be issues with it.

**Comment by maestrith** [comment]
So far...
`if(((code:=UnRedo[ea.name])&&!sc[code])||(sc.2008=sc.2009&&ea.name~="Copy|Cut|Delete")||Clipboard=""&&ea.name="Paste"||sc.2143=0&&sc.2145=sc.2006&&ea.name="Select All"||ea.name="Open Folder"&&Current(2).untitled)if(((code:=UnRedo[ea.name])&&!sc[code])||(sc.2008=sc.2009&&ea.name~="Copy|Cut|Delete")||Clipboard=""&&ea.name="Paste"||sc.2143=0&&sc.2145=sc.2006&&ea.name="Select All"||ea.name="Open Folder"&&Current(2).untitled)`

**Comment by megabugman** [comment]
> I rarely use the mouse

ah ok, I understand then. Open Folder is fixed. 
found another one:
toggle quick find toolbar position should not be available in Global Notes I guess
[![move_to_top.png](https://s14.postimg.org/mvlcxj9e9/move_to_top.png)](https://postimg.org/image/jbzf7q6od/)

**Comment by megabugman** [comment]
Global Notes Context Menu should also have some commands greyed out (I actually am guessing as I dunno exactly what they do).
[![globalnotes.png](https://s11.postimg.org/jh1b05r7n/globalnotes.png)](https://postimg.org/image/v65ao4i67/)

**Comment by megabugman** [comment]
context menu seems broken by now, cut for example not longer working.
[![quicks22.gif](https://s11.postimg.org/dpn6h2xcj/quicks22.gif)](https://postimg.org/image/l5mg2vl1r/)

**Comment by megabugman** [comment]
Split Control Scintilla
- Open Folder does nothing, but is not greyed out.

**Comment by megabugman** [comment]
closed, too many issues in one report.
