### ISSUE TITLE
Download Themes seems not to work

### ISSUE THREAD

**Issue by megabugman** [maestrith/AHK-Studio#99]
Download Themes seems not to work
[![quirk5.gif](https://s10.postimg.org/h8vw2ybkp/quirk5.gif)](https://postimg.org/image/oov5oqz9x/)

**Comment by maestrith** [comment]
I am in the process of re-writing the Themes and Settings in general and I will be fixing the themes downloads.  I have uploaded all the themes into the main directory here named themes.zip

**Comment by megabugman** [comment]
thanks.
